import Link from "next/link";
import { CheckCircle2, Circle, Lock } from "lucide-react";
import type { ModuleDetailResponse } from "@/lib/api/types/newcomer-training";
import { activityStatusLabel } from "@/lib/newcomer-training/presentation";

export function ModuleDetail({ detail }: { detail: ModuleDetailResponse }) {
    const next = detail.module.activities.find((activity) => !activity.completed && !activity.locked);
    return <main className="mx-auto min-h-screen max-w-3xl bg-slate-50 px-4 py-8"><Link href="/newcomer-training" className="text-sm text-slate-600 hover:text-slate-900">← 返回训练路径</Link><header className="mt-5 rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-slate-900">{detail.module.title}</h1><p className="mt-2 text-slate-500">{detail.module.description}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-700">{detail.module.completed_count}/{detail.module.total_required}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${detail.module.percent}%` }} /></div></header><ol className="mt-6 space-y-3">{detail.module.activities.map((activity, index) => <li key={activity.activity_id} className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4">{activity.completed ? <CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-600" /> : activity.locked ? <Lock className="mt-0.5 h-5 w-5 text-slate-400" /> : <Circle className="mt-0.5 h-5 w-5 text-blue-600" />}<div className="min-w-0 flex-1"><p className="text-xs text-slate-400">步骤 {index + 1}</p><p className="font-medium text-slate-900">{activity.title}</p><p className="mt-1 text-sm text-slate-500">{activityStatusLabel(activity)}</p></div>{!activity.locked && <Link href={`/newcomer-training/activities/${encodeURIComponent(activity.activity_id)}`} className="self-center rounded-full px-3 py-2 text-sm font-medium text-blue-700 hover:bg-blue-50">查看</Link>}</li>)}</ol>{next && <div className="sticky bottom-4 mt-6 rounded-2xl border border-blue-100 bg-white/95 p-4 shadow-xl backdrop-blur"><Link href={`/newcomer-training/activities/${encodeURIComponent(next.activity_id)}`} className="flex h-11 w-full items-center justify-center rounded-full bg-slate-900 text-sm font-semibold text-white">继续{next.title}</Link></div>}</main>;
}
