"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { api, getApiErrorMessage } from "@/lib/api/client";
import type { NewcomerExamPaper } from "@/lib/api/types";
import type { ActivityRunnerProps } from "./types";

export function QuizRunner({ detail, onRefresh }: ActivityRunnerProps) {
    const runner = detail.runner.type === "quiz" ? detail.runner : null;
    const [paper, setPaper] = useState<NewcomerExamPaper | null>(null);
    const [answers, setAnswers] = useState<Record<string, string | string[] | boolean>>({});
    const [pending, setPending] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const start = async () => { if (!runner) return; setPending(true); setError(null); try { setPaper(await api.newcomerTraining.getExamPaper(runner.exam_paper_id)); } catch (cause) { setError(getApiErrorMessage(cause)); } finally { setPending(false); } };
    const submit = async () => { if (!paper) return; const missing = paper.questions.some((question) => answers[question.question_id] === undefined || answers[question.question_id] === ""); if (missing) { setError("请完成全部题目后提交。"); return; } setPending(true); setError(null); try { onRefresh?.(await api.newcomerTraining.submitQuiz(detail.activity.activity_id, { client_token: crypto.randomUUID(), answers: paper.questions.map((question) => ({ question_id: question.question_id, answer_payload: answers[question.question_id] })) })); } catch (cause) { setError(getApiErrorMessage(cause)); } finally { setPending(false); } };
    return <div className="space-y-4">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!paper ? <><p className="text-sm text-slate-600">准备好后开始考试，提交后会立即显示结果和下一步。</p><Button isLoading={pending} onClick={() => void start()}>开始答题</Button></> : <form className="space-y-5" onSubmit={(event) => { event.preventDefault(); void submit(); }}>{paper.questions.map((question, index) => <fieldset key={question.question_id} className="rounded-2xl border border-slate-200 p-4"><legend className="px-1 font-semibold text-slate-900">{index + 1}. {question.stem || question.title}</legend>{question.question_type === "true_false" ? <div className="mt-3 flex gap-4">{[["正确", true], ["错误", false]] .map(([label, value]) => <label key={label as string} className="flex items-center gap-2 text-sm"><input type="radio" name={question.question_id} checked={answers[question.question_id] === value} onChange={() => setAnswers((current) => ({ ...current, [question.question_id]: value as boolean }))} />{label as string}</label>)}</div> : question.question_type === "short_answer" ? <textarea aria-label={`第 ${index + 1} 题答案`} className="mt-3 w-full rounded-xl border border-slate-200 px-3 py-2" value={(answers[question.question_id] as string) ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.question_id]: event.target.value }))} /> : <div className="mt-3 space-y-2">{question.options?.map((option) => <label key={option.value} className="flex items-center gap-2 text-sm"><input type={question.question_type === "multiple_choice" ? "checkbox" : "radio"} name={question.question_id} checked={question.question_type === "multiple_choice" ? ((answers[question.question_id] as string[] | undefined) ?? []).includes(option.value) : answers[question.question_id] === option.value} onChange={(event) => setAnswers((current) => question.question_type === "multiple_choice" ? { ...current, [question.question_id]: event.target.checked ? [...((current[question.question_id] as string[] | undefined) ?? []), option.value] : ((current[question.question_id] as string[] | undefined) ?? []).filter((item) => item !== option.value) } : { ...current, [question.question_id]: option.value })} />{option.label}</label>)}</div>}</fieldset>)}<Button type="submit" isLoading={pending}>提交答案</Button></form>}</div>;
}
