"""newcomer journey learning question governance

Revision ID: b9fc04c1ad65
Revises: 20260716_2300_002
Create Date: 2026-07-17 02:59:38.730541

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9fc04c1ad65'
down_revision: str | None = '20260716_2300_002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_command_audits',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=120), nullable=False),
    sa.Column('object_id', sa.String(length=160), nullable=False),
    sa.Column('command', sa.String(length=120), nullable=False),
    sa.Column('before_version', sa.Integer(), nullable=True),
    sa.Column('after_version', sa.Integer(), nullable=True),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('trace_id', sa.String(length=160), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_learning_command_audits_command'), 'learning_command_audits', ['command'], unique=False)
    op.create_index(op.f('ix_learning_command_audits_organization_id'), 'learning_command_audits', ['organization_id'], unique=False)
    op.create_table('learning_questions',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('working_revision_id', sa.String(length=36), nullable=True),
    sa.Column('published_revision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','in_review','approved','published','archived','rejected')", name='ck_learning_question_status'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_learning_question_key')
    )
    op.create_index(op.f('ix_learning_questions_organization_id'), 'learning_questions', ['organization_id'], unique=False)
    op.create_table('learning_quizzes',
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('working_revision_id', sa.String(length=36), nullable=True),
    sa.Column('published_revision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','archived')", name='ck_learning_quiz_status'),
    sa.PrimaryKeyConstraint('quiz_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_learning_quiz_key')
    )
    op.create_index(op.f('ix_learning_quizzes_organization_id'), 'learning_quizzes', ['organization_id'], unique=False)
    op.create_table('learning_source_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('working_revision_id', sa.String(length=36), nullable=True),
    sa.Column('published_revision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','archived')", name='ck_learning_source_document_status'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_learning_source_document_key')
    )
    op.create_index(op.f('ix_learning_source_documents_organization_id'), 'learning_source_documents', ['organization_id'], unique=False)
    op.create_table('learning_units_v2',
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('working_revision_id', sa.String(length=36), nullable=True),
    sa.Column('published_revision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','archived')", name='ck_learning_unit_status_v2'),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_learning_unit_key_v2')
    )
    op.create_index(op.f('ix_learning_units_v2_organization_id'), 'learning_units_v2', ['organization_id'], unique=False)
    op.create_table('newcomer_command_audits',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=120), nullable=False),
    sa.Column('object_id', sa.String(length=160), nullable=False),
    sa.Column('command', sa.String(length=120), nullable=False),
    sa.Column('before_version', sa.Integer(), nullable=True),
    sa.Column('after_version', sa.Integer(), nullable=True),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('expected_version', sa.Integer(), nullable=True),
    sa.Column('actual_version', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('preview_token_hash', sa.String(length=64), nullable=True),
    sa.Column('impact_hash', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=160), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_newcomer_command_audits_actor_id'), 'newcomer_command_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_newcomer_command_audits_command'), 'newcomer_command_audits', ['command'], unique=False)
    op.create_index(op.f('ix_newcomer_command_audits_organization_id'), 'newcomer_command_audits', ['organization_id'], unique=False)
    op.create_table('newcomer_paths',
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('working_revision_id', sa.String(length=36), nullable=True),
    sa.Column('published_revision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','archived')", name='ck_newcomer_paths_status'),
    sa.PrimaryKeyConstraint('path_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_newcomer_paths_org_key')
    )
    op.create_index(op.f('ix_newcomer_paths_organization_id'), 'newcomer_paths', ['organization_id'], unique=False)
    op.create_table('learning_quiz_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('question_revision_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('save_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('save_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('publish_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('publish_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('working','published','archived')", name='ck_learning_quiz_revision_status'),
    sa.ForeignKeyConstraint(['quiz_id'], ['learning_quizzes.quiz_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('quiz_id', 'revision_no', name='uq_learning_quiz_revision_number')
    )
    op.create_index(op.f('ix_learning_quiz_revisions_organization_id'), 'learning_quiz_revisions', ['organization_id'], unique=False)
    op.create_table('learning_source_document_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=120), nullable=False),
    sa.Column('parse_status', sa.String(length=24), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('save_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('save_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('publish_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('publish_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("parse_status IN ('pending','ready','failed')", name='ck_learning_source_revision_parse_status'),
    sa.CheckConstraint("status IN ('working','published','archived')", name='ck_learning_source_revision_status'),
    sa.ForeignKeyConstraint(['document_id'], ['learning_source_documents.document_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('document_id', 'revision_no', name='uq_learning_source_revision_number')
    )
    op.create_index(op.f('ix_learning_source_document_revisions_organization_id'), 'learning_source_document_revisions', ['organization_id'], unique=False)
    op.create_table('learning_unit_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_anchor_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('save_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('save_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('publish_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('publish_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('working','published','archived')", name='ck_learning_unit_revision_status'),
    sa.ForeignKeyConstraint(['unit_id'], ['learning_units_v2.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('unit_id', 'revision_no', name='uq_learning_unit_revision_number')
    )
    op.create_index(op.f('ix_learning_unit_revisions_organization_id'), 'learning_unit_revisions', ['organization_id'], unique=False)
    op.create_table('newcomer_path_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('revision_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('save_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('save_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('publish_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('publish_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('working','published','archived')", name='ck_newcomer_path_revisions_status'),
    sa.ForeignKeyConstraint(['path_id'], ['newcomer_paths.path_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('path_id', 'revision_no', name='uq_newcomer_path_revision_number')
    )
    op.create_index(op.f('ix_newcomer_path_revisions_organization_id'), 'newcomer_path_revisions', ['organization_id'], unique=False)
    op.create_index('ix_newcomer_path_revisions_path_status', 'newcomer_path_revisions', ['path_id', 'status'], unique=False)
    op.create_table('learning_lesson_attempts',
    sa.Column('detail_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('learner_id', sa.String(length=120), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('path_revision_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=160), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('learning_unit_revision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('required_checkpoint_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed_checkpoint_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reading_position_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('relearn_of_detail_id', sa.String(length=36), nullable=True),
    sa.Column('start_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('start_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','completed','invalidated')", name='ck_learning_lesson_attempt_status'),
    sa.ForeignKeyConstraint(['learning_unit_revision_id'], ['learning_unit_revisions.revision_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['relearn_of_detail_id'], ['learning_lesson_attempts.detail_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_learning_lesson_attempts_enrollment_id'), 'learning_lesson_attempts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_learning_lesson_attempts_learner_id'), 'learning_lesson_attempts', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learning_lesson_attempts_organization_id'), 'learning_lesson_attempts', ['organization_id'], unique=False)
    op.create_index('ix_learning_lesson_enrollment_activity', 'learning_lesson_attempts', ['enrollment_id', 'activity_id', 'started_at'], unique=False)
    op.create_table('learning_question_generation_batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('learning_unit_revision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=160), nullable=False),
    sa.Column('prompt_revision_id', sa.String(length=160), nullable=False),
    sa.Column('prompt_contract_hash', sa.String(length=80), nullable=False),
    sa.Column('model_routing_profile_id', sa.String(length=160), nullable=False),
    sa.Column('model_routing_revision_id', sa.String(length=160), nullable=False),
    sa.Column('input_schema_version', sa.String(length=120), nullable=False),
    sa.Column('output_schema_version', sa.String(length=120), nullable=False),
    sa.Column('generation_input_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('invocation_id', sa.String(length=160), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')", name='ck_learning_question_batch_status'),
    sa.ForeignKeyConstraint(['learning_unit_revision_id'], ['learning_unit_revisions.revision_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_revision_id'], ['learning_source_document_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key_hash', name='uq_learning_question_batch_idempotency')
    )
    op.create_index(op.f('ix_learning_question_generation_batches_organization_id'), 'learning_question_generation_batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_question_generation_batches_task_id'), 'learning_question_generation_batches', ['task_id'], unique=False)
    op.create_table('learning_quiz_attempts',
    sa.Column('detail_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('learner_id', sa.String(length=120), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('path_revision_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=160), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_revision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rule_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('answers_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('objective_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('scoring_invocation_id', sa.String(length=160), nullable=True),
    sa.Column('scoring_evidence_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_error_code', sa.String(length=120), nullable=True),
    sa.Column('start_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('start_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','scoring_pending','needs_review','scored','invalidated','cancelled')", name='ck_learning_quiz_attempt_status'),
    sa.ForeignKeyConstraint(['quiz_revision_id'], ['learning_quiz_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_learning_quiz_attempts_enrollment_id'), 'learning_quiz_attempts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_learning_quiz_attempts_learner_id'), 'learning_quiz_attempts', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learning_quiz_attempts_organization_id'), 'learning_quiz_attempts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_quiz_attempts_task_id'), 'learning_quiz_attempts', ['task_id'], unique=False)
    op.create_index('ix_learning_quiz_enrollment_activity', 'learning_quiz_attempts', ['enrollment_id', 'activity_id', 'started_at'], unique=False)
    op.create_table('learning_source_anchors',
    sa.Column('anchor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('anchor_key', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('locator_type', sa.String(length=24), nullable=False),
    sa.Column('locator_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excerpt_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_revision_id'], ['learning_source_document_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('anchor_id'),
    sa.UniqueConstraint('source_revision_id', 'anchor_key', name='uq_learning_source_anchor_key')
    )
    op.create_index(op.f('ix_learning_source_anchors_organization_id'), 'learning_source_anchors', ['organization_id'], unique=False)
    op.create_table('newcomer_cohorts',
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path_revision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','closed','archived')", name='ck_newcomer_cohorts_status'),
    sa.ForeignKeyConstraint(['path_revision_id'], ['newcomer_path_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cohort_id'),
    sa.UniqueConstraint('organization_id', 'stable_key', name='uq_newcomer_cohorts_org_key')
    )
    op.create_index(op.f('ix_newcomer_cohorts_organization_id'), 'newcomer_cohorts', ['organization_id'], unique=False)
    op.create_table('newcomer_enrollment_migrations',
    sa.Column('migration_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('target_revision_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('preview_token_hash', sa.String(length=64), nullable=False),
    sa.Column('impact_hash', sa.String(length=64), nullable=False),
    sa.Column('preview_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confirm_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('confirm_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('previewed','succeeded','partial','failed','expired')", name='ck_newcomer_enrollment_migrations_status'),
    sa.ForeignKeyConstraint(['target_revision_id'], ['newcomer_path_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('migration_id'),
    sa.UniqueConstraint('preview_token_hash')
    )
    op.create_index(op.f('ix_newcomer_enrollment_migrations_organization_id'), 'newcomer_enrollment_migrations', ['organization_id'], unique=False)
    op.create_table('learning_lesson_commands',
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('detail_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('command_type', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('result_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['learning_lesson_attempts.detail_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('command_id'),
    sa.UniqueConstraint('detail_id', 'command_type', 'idempotency_key_hash', name='uq_learning_lesson_command_idempotency')
    )
    op.create_table('learning_question_candidates',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_anchor_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('competency_keys_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deterministic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('gate_status', sa.String(length=24), nullable=False),
    sa.Column('gate_results_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_revision_id', sa.String(length=160), nullable=False),
    sa.Column('model_routing_revision_id', sa.String(length=160), nullable=False),
    sa.Column('generation_input_hash', sa.String(length=64), nullable=False),
    sa.Column('invocation_id', sa.String(length=160), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('review_idempotency_key_hash', sa.String(length=64), nullable=True),
    sa.Column('review_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('approved_question_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gate_status IN ('passed','failed')", name='ck_learning_question_candidate_gate_status'),
    sa.CheckConstraint("status IN ('generated','in_review','approved','rejected','superseded')", name='ck_learning_question_candidate_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['learning_question_generation_batches.batch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('ix_learning_question_candidate_queue', 'learning_question_candidates', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_question_candidates_deterministic_fingerprint'), 'learning_question_candidates', ['deterministic_fingerprint'], unique=False)
    op.create_index(op.f('ix_learning_question_candidates_organization_id'), 'learning_question_candidates', ['organization_id'], unique=False)
    op.create_table('learning_quiz_commands',
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('detail_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('command_type', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('result_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['learning_quiz_attempts.detail_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('command_id'),
    sa.UniqueConstraint('detail_id', 'command_type', 'idempotency_key_hash', name='uq_learning_quiz_command_idempotency')
    )
    op.create_table('newcomer_enrollments_v2',
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('path_revision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.String(length=120), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','cancelled')", name='ck_newcomer_enrollments_v2_status'),
    sa.ForeignKeyConstraint(['cohort_id'], ['newcomer_cohorts.cohort_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['path_revision_id'], ['newcomer_path_revisions.revision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('organization_id', 'cohort_id', 'learner_id', name='uq_newcomer_enrollment_cohort_learner')
    )
    op.create_index(op.f('ix_newcomer_enrollments_v2_organization_id'), 'newcomer_enrollments_v2', ['organization_id'], unique=False)
    op.create_index('uq_newcomer_enrollments_v2_active_learner', 'newcomer_enrollments_v2', ['organization_id', 'learner_id'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_table('learning_question_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_anchor_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('competency_keys_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deterministic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','in_review','approved','published','archived','rejected')", name='ck_learning_question_revision_status'),
    sa.ForeignKeyConstraint(['question_id'], ['learning_questions.question_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['learning_question_candidates.candidate_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('question_id', 'revision_no', name='uq_learning_question_revision_number')
    )
    op.create_index(op.f('ix_learning_question_revisions_deterministic_fingerprint'), 'learning_question_revisions', ['deterministic_fingerprint'], unique=False)
    op.create_index(op.f('ix_learning_question_revisions_organization_id'), 'learning_question_revisions', ['organization_id'], unique=False)
    op.create_table('newcomer_activity_attempts_v2',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('path_revision_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=160), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activity_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('command_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result_type', sa.String(length=120), nullable=True),
    sa.Column('result_id', sa.String(length=160), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('outcome_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('reconcile_status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('started','in_progress','submitted','processing','completed','failed','invalidated','cancelled')", name='ck_newcomer_activity_attempts_v2_status'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['newcomer_enrollments_v2.enrollment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('enrollment_id', 'activity_id', 'attempt_no', name='uq_newcomer_activity_attempt_number_v2'),
    sa.UniqueConstraint('organization_id', 'enrollment_id', 'activity_id', 'idempotency_key_hash', name='uq_newcomer_activity_attempt_command_v2')
    )
    op.create_index(op.f('ix_newcomer_activity_attempts_v2_organization_id'), 'newcomer_activity_attempts_v2', ['organization_id'], unique=False)
    op.create_table('newcomer_activity_outcomes',
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=120), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('result_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_result', sa.String(length=32), nullable=False),
    sa.Column('assessment_result', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('competency_evidence_refs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_refs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lineage_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('critical_flags_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('degradations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_action_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['newcomer_activity_attempts_v2.attempt_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outcome_id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_newcomer_activity_outcomes_organization_id'), 'newcomer_activity_outcomes', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newcomer_activity_outcomes_organization_id'), table_name='newcomer_activity_outcomes')
    op.drop_table('newcomer_activity_outcomes')
    op.drop_index(op.f('ix_newcomer_activity_attempts_v2_organization_id'), table_name='newcomer_activity_attempts_v2')
    op.drop_table('newcomer_activity_attempts_v2')
    op.drop_index(op.f('ix_learning_question_revisions_organization_id'), table_name='learning_question_revisions')
    op.drop_index(op.f('ix_learning_question_revisions_deterministic_fingerprint'), table_name='learning_question_revisions')
    op.drop_table('learning_question_revisions')
    op.drop_index('uq_newcomer_enrollments_v2_active_learner', table_name='newcomer_enrollments_v2', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_newcomer_enrollments_v2_organization_id'), table_name='newcomer_enrollments_v2')
    op.drop_table('newcomer_enrollments_v2')
    op.drop_table('learning_quiz_commands')
    op.drop_index(op.f('ix_learning_question_candidates_organization_id'), table_name='learning_question_candidates')
    op.drop_index(op.f('ix_learning_question_candidates_deterministic_fingerprint'), table_name='learning_question_candidates')
    op.drop_index('ix_learning_question_candidate_queue', table_name='learning_question_candidates')
    op.drop_table('learning_question_candidates')
    op.drop_table('learning_lesson_commands')
    op.drop_index(op.f('ix_newcomer_enrollment_migrations_organization_id'), table_name='newcomer_enrollment_migrations')
    op.drop_table('newcomer_enrollment_migrations')
    op.drop_index(op.f('ix_newcomer_cohorts_organization_id'), table_name='newcomer_cohorts')
    op.drop_table('newcomer_cohorts')
    op.drop_index(op.f('ix_learning_source_anchors_organization_id'), table_name='learning_source_anchors')
    op.drop_table('learning_source_anchors')
    op.drop_index('ix_learning_quiz_enrollment_activity', table_name='learning_quiz_attempts')
    op.drop_index(op.f('ix_learning_quiz_attempts_task_id'), table_name='learning_quiz_attempts')
    op.drop_index(op.f('ix_learning_quiz_attempts_organization_id'), table_name='learning_quiz_attempts')
    op.drop_index(op.f('ix_learning_quiz_attempts_learner_id'), table_name='learning_quiz_attempts')
    op.drop_index(op.f('ix_learning_quiz_attempts_enrollment_id'), table_name='learning_quiz_attempts')
    op.drop_table('learning_quiz_attempts')
    op.drop_index(op.f('ix_learning_question_generation_batches_task_id'), table_name='learning_question_generation_batches')
    op.drop_index(op.f('ix_learning_question_generation_batches_organization_id'), table_name='learning_question_generation_batches')
    op.drop_table('learning_question_generation_batches')
    op.drop_index('ix_learning_lesson_enrollment_activity', table_name='learning_lesson_attempts')
    op.drop_index(op.f('ix_learning_lesson_attempts_organization_id'), table_name='learning_lesson_attempts')
    op.drop_index(op.f('ix_learning_lesson_attempts_learner_id'), table_name='learning_lesson_attempts')
    op.drop_index(op.f('ix_learning_lesson_attempts_enrollment_id'), table_name='learning_lesson_attempts')
    op.drop_table('learning_lesson_attempts')
    op.drop_index('ix_newcomer_path_revisions_path_status', table_name='newcomer_path_revisions')
    op.drop_index(op.f('ix_newcomer_path_revisions_organization_id'), table_name='newcomer_path_revisions')
    op.drop_table('newcomer_path_revisions')
    op.drop_index(op.f('ix_learning_unit_revisions_organization_id'), table_name='learning_unit_revisions')
    op.drop_table('learning_unit_revisions')
    op.drop_index(op.f('ix_learning_source_document_revisions_organization_id'), table_name='learning_source_document_revisions')
    op.drop_table('learning_source_document_revisions')
    op.drop_index(op.f('ix_learning_quiz_revisions_organization_id'), table_name='learning_quiz_revisions')
    op.drop_table('learning_quiz_revisions')
    op.drop_index(op.f('ix_newcomer_paths_organization_id'), table_name='newcomer_paths')
    op.drop_table('newcomer_paths')
    op.drop_index(op.f('ix_newcomer_command_audits_organization_id'), table_name='newcomer_command_audits')
    op.drop_index(op.f('ix_newcomer_command_audits_command'), table_name='newcomer_command_audits')
    op.drop_index(op.f('ix_newcomer_command_audits_actor_id'), table_name='newcomer_command_audits')
    op.drop_table('newcomer_command_audits')
    op.drop_index(op.f('ix_learning_units_v2_organization_id'), table_name='learning_units_v2')
    op.drop_table('learning_units_v2')
    op.drop_index(op.f('ix_learning_source_documents_organization_id'), table_name='learning_source_documents')
    op.drop_table('learning_source_documents')
    op.drop_index(op.f('ix_learning_quizzes_organization_id'), table_name='learning_quizzes')
    op.drop_table('learning_quizzes')
    op.drop_index(op.f('ix_learning_questions_organization_id'), table_name='learning_questions')
    op.drop_table('learning_questions')
    op.drop_index(op.f('ix_learning_command_audits_organization_id'), table_name='learning_command_audits')
    op.drop_index(op.f('ix_learning_command_audits_command'), table_name='learning_command_audits')
    op.drop_table('learning_command_audits')
    # ### end Alembic commands ###
