"""Create the durable task runtime and governed AI platform persistence.

Revision ID: 20260716_2300_002
Revises: 20260715_0000_001
Create Date: 2026-07-17 01:03:49.700114

"""

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision: str = "20260716_2300_002"
down_revision: str | None = "20260715_0000_001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TASK_RUNTIME_PERMISSION_ROWS: tuple[dict[str, str], ...] = (
    {
        "id": "5dd8af58-8278-55b8-b651-bec1eaa79001",
        "role": "admin",
        "permission": "task_runtime.read",
    },
    {
        "id": "5dd8af58-8278-55b8-b651-bec1eaa79002",
        "role": "admin",
        "permission": "task_runtime.operate",
    },
)


def _admin_role_permissions_table() -> sa.TableClause:
    return sa.table(
        "admin_role_permissions",
        sa.column("id", sa.String(length=36)),
        sa.column("role", sa.String(length=20)),
        sa.column("permission", sa.String(length=80)),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )


def _seed_task_runtime_permissions() -> None:
    """Insert only missing logical permissions and remain replay-safe."""

    table = _admin_role_permissions_table()
    values: list[dict[str, Any]] = [
        {**row, "created_at": sa.func.now()} for row in _TASK_RUNTIME_PERMISSION_ROWS
    ]
    dialect_name = op.get_bind().dialect.name
    if dialect_name == "postgresql":
        statement = postgresql.insert(table).values(values).on_conflict_do_nothing()
    elif dialect_name == "sqlite":
        statement = sqlite.insert(table).values(values).on_conflict_do_nothing()
    else:  # pragma: no cover - production and migration tests use PostgreSQL/SQLite
        for value in values:
            exists = op.get_bind().execute(
                sa.select(table.c.id).where(
                    sa.or_(
                        table.c.id == value["id"],
                        sa.and_(
                            table.c.role == value["role"],
                            table.c.permission == value["permission"],
                        ),
                    )
                )
            )
            if exists.scalar_one_or_none() is None:
                op.execute(sa.insert(table).values(**value))
        return
    op.execute(statement)


def _remove_task_runtime_permission_seeds() -> None:
    """Delete only rows owned by this revision, preserving operator-created rows."""

    table = _admin_role_permissions_table()
    predicates = [
        sa.and_(
            table.c.id == row["id"],
            table.c.role == row["role"],
            table.c.permission == row["permission"],
        )
        for row in _TASK_RUNTIME_PERMISSION_ROWS
    ]
    op.execute(sa.delete(table).where(sa.or_(*predicates)))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_budget_windows",
        sa.Column("window_id", sa.String(length=36), nullable=False),
        sa.Column("model_routing_revision_id", sa.String(length=160), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_key", sa.String(length=160), nullable=False),
        sa.Column("business_purpose", sa.String(length=160), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("limit_minor_units", sa.Integer(), nullable=False),
        sa.Column("reserved_minor_units", sa.Integer(), nullable=False),
        sa.Column("consumed_minor_units", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("window_id"),
        sa.UniqueConstraint(
            "model_routing_revision_id",
            "scope_type",
            "scope_key",
            "business_purpose",
            "window_start",
            name="uq_ai_budget_windows_scope",
        ),
    )
    op.create_table(
        "ai_circuit_states",
        sa.Column("circuit_id", sa.String(length=36), nullable=False),
        sa.Column("model_routing_revision_id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("opened_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("circuit_id"),
        sa.UniqueConstraint(
            "model_routing_revision_id",
            "provider",
            "model",
            name="uq_ai_circuit_states_route",
        ),
    )
    op.create_table(
        "ai_model_routing_profiles",
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=160), nullable=False),
        sa.Column("revision_id", sa.String(length=160), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "snapshot_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('published','archived')",
            name="ck_ai_model_routing_profiles_status",
        ),
        sa.PrimaryKeyConstraint("record_id"),
        sa.UniqueConstraint(
            "profile_id", "revision_id", name="uq_ai_model_routing_profiles_exact"
        ),
        sa.UniqueConstraint(
            "profile_id", "revision_no", name="uq_ai_model_routing_profiles_number"
        ),
    )
    op.create_table(
        "ai_prompt_revisions",
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=160), nullable=False),
        sa.Column("revision_id", sa.String(length=160), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("business_purpose", sa.String(length=160), nullable=False),
        sa.Column("template_text", sa.Text(), nullable=False),
        sa.Column(
            "variables_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("input_schema_version", sa.String(length=120), nullable=False),
        sa.Column("output_schema_version", sa.String(length=120), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('published','archived')", name="ck_ai_prompt_revisions_status"
        ),
        sa.PrimaryKeyConstraint("record_id"),
        sa.UniqueConstraint(
            "template_id", "revision_id", name="uq_ai_prompt_revisions_exact"
        ),
        sa.UniqueConstraint(
            "template_id", "revision_no", name="uq_ai_prompt_revisions_number"
        ),
    )
    op.create_table(
        "ai_rate_limit_windows",
        sa.Column("window_id", sa.String(length=36), nullable=False),
        sa.Column("model_routing_revision_id", sa.String(length=160), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_key", sa.String(length=160), nullable=False),
        sa.Column("business_purpose", sa.String(length=160), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("request_limit", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("window_id"),
        sa.UniqueConstraint(
            "model_routing_revision_id",
            "scope_type",
            "scope_key",
            "business_purpose",
            "window_start",
            name="uq_ai_rate_limit_windows_scope",
        ),
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=True),
        sa.Column("trace_id", sa.String(length=160), nullable=True),
        sa.Column("correlation_id", sa.String(length=160), nullable=False),
        sa.Column("causation_id", sa.String(length=160), nullable=True),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("aggregate_type", sa.String(length=120), nullable=False),
        sa.Column("aggregate_id", sa.String(length=160), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint(
            "organization_id",
            "event_type",
            "idempotency_key",
            name="uq_outbox_events_logical_event",
        ),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"),
        "outbox_events",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_available_at"),
        "outbox_events",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_dead_lettered_at"),
        "outbox_events",
        ["dead_lettered_at"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_events_dispatch",
        "outbox_events",
        ["published_at", "dead_lettered_at", "available_at", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"),
        "outbox_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_lease_expires_at"),
        "outbox_events",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_lease_owner"),
        "outbox_events",
        ["lease_owner"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_occurred_at"),
        "outbox_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_organization_id"),
        "outbox_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_published_at"),
        "outbox_events",
        ["published_at"],
        unique=False,
    )
    op.create_table(
        "task_operator_scope_grants",
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=160), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_operate", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("granted_by", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=120), nullable=True),
        sa.Column("revocation_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(resource_type = '' AND resource_id = '') OR (resource_type <> '' AND resource_id <> '')",
            name="ck_task_operator_scope_grants_shape",
        ),
        sa.CheckConstraint(
            "granted_by <> '' AND reason <> ''",
            name="ck_task_operator_scope_grants_audit_required",
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revocation_reason IS NOT NULL)",
            name="ck_task_operator_scope_grants_revocation_audit",
        ),
        sa.CheckConstraint(
            "expires_at > created_at",
            name="ck_task_operator_scope_grants_future_expiry",
        ),
        sa.PrimaryKeyConstraint("grant_id"),
    )
    op.create_index(
        op.f("ix_task_operator_scope_grants_actor_id"),
        "task_operator_scope_grants",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_operator_scope_grants_expires_at"),
        "task_operator_scope_grants",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_task_operator_scope_grants_lookup",
        "task_operator_scope_grants",
        ["actor_id", "organization_id", "resource_type", "resource_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_operator_scope_grants_organization_id"),
        "task_operator_scope_grants",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "task_payload_artifacts",
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("data_classification", sa.String(length=40), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index(
        op.f("ix_task_payload_artifacts_organization_id"),
        "task_payload_artifacts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "task_type_control_commands",
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("task_type", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("command_id"),
        sa.UniqueConstraint(
            "organization_id",
            "task_type",
            "action",
            "idempotency_key_hash",
            name="uq_task_type_control_commands_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_task_type_control_commands_organization_id"),
        "task_type_control_commands",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_type_control_commands_task_type"),
        "task_type_control_commands",
        ["task_type"],
        unique=False,
    )
    op.create_table(
        "task_type_controls",
        sa.Column("control_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("task_type", sa.String(length=120), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("updated_by", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "max_concurrency IS NULL OR max_concurrency > 0",
            name="ck_task_type_controls_max_concurrency_positive",
        ),
        sa.CheckConstraint(
            "rate_limit_per_minute IS NULL OR rate_limit_per_minute > 0",
            name="ck_task_type_controls_rate_limit_positive",
        ),
        sa.PrimaryKeyConstraint("control_id"),
        sa.UniqueConstraint(
            "organization_id", "task_type", name="uq_task_type_controls_org_type"
        ),
    )
    op.create_index(
        op.f("ix_task_type_controls_organization_id"),
        "task_type_controls",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_type_controls_task_type"),
        "task_type_controls",
        ["task_type"],
        unique=False,
    )
    op.create_table(
        "durable_tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.String(length=120), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("input_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "retry_policy_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=160), nullable=False),
        sa.Column("causation_id", sa.String(length=160), nullable=True),
        sa.Column("trace_id", sa.String(length=160), nullable=True),
        sa.Column("last_error_code", sa.String(length=120), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("fence_generation", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued','running','retry_wait','cancel_requested','cancelled','succeeded','dead_letter')",
            name="ck_durable_tasks_state",
        ),
        sa.CheckConstraint(
            "priority BETWEEN 0 AND 100", name="ck_durable_tasks_priority"
        ),
        sa.ForeignKeyConstraint(
            ["input_artifact_id"],
            ["task_payload_artifacts.artifact_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_id"),
        sa.UniqueConstraint(
            "organization_id",
            "task_type",
            "resource_type",
            "resource_id",
            "idempotency_key_hash",
            name="uq_durable_tasks_business_object_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_durable_tasks_actor_id"), "durable_tasks", ["actor_id"], unique=False
    )
    op.create_index(
        "ix_durable_tasks_claim",
        "durable_tasks",
        [
            "state",
            sa.literal_column("priority DESC"),
            "next_run_at",
            "created_at",
            "task_id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_durable_tasks_type_claim",
        "durable_tasks",
        [
            "task_type",
            "state",
            sa.literal_column("priority DESC"),
            "next_run_at",
            "created_at",
            "task_id",
        ],
        unique=False,
    )
    op.create_index(
        "ix_durable_tasks_aged_claim",
        "durable_tasks",
        ["state", "created_at", "next_run_at", "task_id"],
        unique=False,
    )
    op.create_index(
        "ix_durable_tasks_type_aged_claim",
        "durable_tasks",
        [
            "task_type",
            "state",
            "created_at",
            "next_run_at",
            "task_id",
        ],
        unique=False,
    )
    op.create_index(
        op.f("ix_durable_tasks_correlation_id"),
        "durable_tasks",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_durable_tasks_next_run_at"),
        "durable_tasks",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        "ix_durable_tasks_org_updated_keyset",
        "durable_tasks",
        [
            "organization_id",
            sa.literal_column("updated_at DESC"),
            sa.literal_column("task_id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        op.f("ix_durable_tasks_organization_id"),
        "durable_tasks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_durable_tasks_resource",
        "durable_tasks",
        ["organization_id", "resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_durable_tasks_state"), "durable_tasks", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_durable_tasks_task_type"), "durable_tasks", ["task_type"], unique=False
    )
    op.create_index(
        op.f("ix_durable_tasks_trace_id"), "durable_tasks", ["trace_id"], unique=False
    )
    op.create_table(
        "outbox_consumer_receipts",
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("consumer_name", sa.String(length=160), nullable=False),
        sa.Column("handler_version", sa.String(length=80), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["outbox_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint(
            "consumer_name", "event_id", name="uq_outbox_consumer_receipts_effect_once"
        ),
    )
    op.create_index(
        op.f("ix_outbox_consumer_receipts_event_id"),
        "outbox_consumer_receipts",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "ai_invocations",
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("business_purpose", sa.String(length=160), nullable=False),
        sa.Column("object_type", sa.String(length=120), nullable=False),
        sa.Column("object_id", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=80), nullable=False),
        sa.Column("data_classification", sa.String(length=40), nullable=False),
        sa.Column("workload_kind", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("owner_token_hash", sa.String(length=64), nullable=True),
        sa.Column("owner_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prompt_template_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_revision_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_contract_hash", sa.String(length=80), nullable=True),
        sa.Column("asr_profile_revision_id", sa.String(length=160), nullable=True),
        sa.Column("input_artifact_ref", sa.String(length=500), nullable=True),
        sa.Column("model_routing_profile_id", sa.String(length=160), nullable=False),
        sa.Column("model_routing_revision_id", sa.String(length=160), nullable=False),
        sa.Column("input_schema_version", sa.String(length=120), nullable=False),
        sa.Column("output_schema_version", sa.String(length=120), nullable=False),
        sa.Column("timeout_policy_ref", sa.String(length=160), nullable=False),
        sa.Column("retry_policy_ref", sa.String(length=160), nullable=False),
        sa.Column("budget_scope", sa.String(length=32), nullable=False),
        sa.Column("runtime_consumer", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("provider_request_id", sa.String(length=240), nullable=True),
        sa.Column("finish_reason", sa.String(length=80), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_minor_units", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("output_validation_attempts", sa.Integer(), nullable=False),
        sa.Column("result_artifact_id", sa.String(length=36), nullable=True),
        sa.Column(
            "evidence_refs_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "degradations_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_classification", sa.String(length=80), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=160), nullable=False),
        sa.Column("correlation_id", sa.String(length=160), nullable=False),
        sa.Column("causation_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(workload_kind = 'llm' AND prompt_template_id IS NOT NULL AND prompt_revision_id IS NOT NULL AND prompt_contract_hash IS NOT NULL AND asr_profile_revision_id IS NULL AND input_artifact_ref IS NULL) OR (workload_kind = 'asr' AND prompt_template_id IS NULL AND prompt_revision_id IS NULL AND prompt_contract_hash IS NULL AND asr_profile_revision_id IS NOT NULL AND input_artifact_ref IS NOT NULL)",
            name="ck_ai_invocations_workload_lineage",
        ),
        sa.CheckConstraint(
            "state IN ('prepared','running','succeeded','partial','failed')",
            name="ck_ai_invocations_state",
        ),
        sa.CheckConstraint(
            "workload_kind IN ('llm','asr')", name="ck_ai_invocations_workload_kind"
        ),
        sa.ForeignKeyConstraint(
            ["result_artifact_id"],
            ["ai_invocation_artifacts.artifact_id"],
            name="fk_ai_invocations_result_artifact",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["durable_tasks.task_id"],
            name="fk_ai_invocations_task",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("invocation_id"),
        sa.UniqueConstraint(
            "organization_id",
            "business_purpose",
            "object_type",
            "object_id",
            "idempotency_key_hash",
            name="uq_ai_invocations_logical_request",
        ),
    )
    op.create_index(
        op.f("ix_ai_invocations_actor_id"), "ai_invocations", ["actor_id"], unique=False
    )
    op.create_index(
        "ix_ai_invocations_business_object",
        "ai_invocations",
        ["organization_id", "object_type", "object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_invocations_business_purpose"),
        "ai_invocations",
        ["business_purpose"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_invocations_correlation_id"),
        "ai_invocations",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_invocations_organization_id"),
        "ai_invocations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_invocations_owner_expires_at"),
        "ai_invocations",
        ["owner_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_invocations_state"), "ai_invocations", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_ai_invocations_task_id"), "ai_invocations", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_invocations_trace_id"), "ai_invocations", ["trace_id"], unique=False
    )
    op.create_table(
        "task_attempts",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=160), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_classification", sa.String(length=80), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["durable_tasks.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint("task_id", "attempt_no", name="uq_task_attempts_task_no"),
    )
    op.create_index(
        "ix_task_attempts_started_task",
        "task_attempts",
        ["started_at", "task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_attempts_task_id"), "task_attempts", ["task_id"], unique=False
    )
    op.create_table(
        "task_command_records",
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("command_type", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result_state", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["durable_tasks.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("command_id"),
        sa.UniqueConstraint(
            "task_id",
            "command_type",
            "idempotency_key_hash",
            name="uq_task_command_records_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_task_command_records_organization_id"),
        "task_command_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_command_records_task_id"),
        "task_command_records",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_progress",
        sa.Column("progress_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("current", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=120), nullable=True),
        sa.Column("label", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "current IS NULL OR current >= 0",
            name="ck_task_progress_current_non_negative",
        ),
        sa.CheckConstraint(
            "current IS NULL OR total IS NULL OR current <= total",
            name="ck_task_progress_bounds",
        ),
        sa.CheckConstraint(
            "total IS NULL OR total > 0", name="ck_task_progress_total_positive"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["durable_tasks.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("progress_id"),
        sa.UniqueConstraint("task_id", "sequence", name="uq_task_progress_sequence"),
    )
    op.create_index(
        op.f("ix_task_progress_task_id"), "task_progress", ["task_id"], unique=False
    )
    op.create_table(
        "task_result_refs",
        sa.Column("result_ref_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("result_kind", sa.String(length=32), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=160), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column(
            "saved_items_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "remaining_items_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "retryable_items_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "result_kind IN ('complete','partial_success','waiting_input')",
            name="ck_task_result_refs_kind",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["durable_tasks.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("result_ref_id"),
    )
    op.create_index(
        op.f("ix_task_result_refs_task_id"),
        "task_result_refs",
        ["task_id"],
        unique=True,
    )
    op.create_table(
        "ai_budget_reservations",
        sa.Column("reservation_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("window_id", sa.String(length=36), nullable=False),
        sa.Column("reserved_minor_units", sa.Integer(), nullable=False),
        sa.Column("actual_minor_units", sa.Integer(), nullable=False),
        sa.Column("released_minor_units", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('reserved','finalized','released')",
            name="ck_ai_budget_reservations_state",
        ),
        sa.ForeignKeyConstraint(
            ["invocation_id"], ["ai_invocations.invocation_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["window_id"], ["ai_budget_windows.window_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_ai_budget_reservations_invocation_id"),
        "ai_budget_reservations",
        ["invocation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ai_budget_reservations_window_id"),
        "ai_budget_reservations",
        ["window_id"],
        unique=False,
    )
    op.create_table(
        "ai_invocation_artifacts",
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("artifact_kind", sa.String(length=40), nullable=False),
        sa.Column("data_classification", sa.String(length=40), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "validated_payload_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invocation_id"], ["ai_invocations.invocation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index(
        op.f("ix_ai_invocation_artifacts_invocation_id"),
        "ai_invocation_artifacts",
        ["invocation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ai_invocation_artifacts_organization_id"),
        "ai_invocation_artifacts",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_ai_invocations_result_artifact",
        "ai_invocations",
        "ai_invocation_artifacts",
        ["result_artifact_id"],
        ["artifact_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_table(
        "ai_provider_attempts",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("provider_idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("route_kind", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("provider_request_id", sa.String(length=240), nullable=True),
        sa.Column("finish_reason", sa.String(length=80), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_classification", sa.String(length=80), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "route_kind IN ('primary','fallback')",
            name="ck_ai_provider_attempts_route_kind",
        ),
        sa.CheckConstraint(
            "state IN ('invoking','responded','failed')",
            name="ck_ai_provider_attempts_state",
        ),
        sa.ForeignKeyConstraint(
            ["invocation_id"], ["ai_invocations.invocation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        sa.UniqueConstraint(
            "invocation_id", "attempt_no", name="uq_ai_provider_attempts_number"
        ),
        sa.UniqueConstraint("provider_idempotency_key"),
    )
    op.create_index(
        op.f("ix_ai_provider_attempts_invocation_id"),
        "ai_provider_attempts",
        ["invocation_id"],
        unique=False,
    )
    op.create_table(
        "task_leases",
        sa.Column("lease_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("lease_token_hash", sa.String(length=64), nullable=False),
        sa.Column("fence_generation", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(length=160), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("renewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["task_attempts.attempt_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["durable_tasks.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("lease_id"),
        sa.UniqueConstraint("attempt_id"),
        sa.UniqueConstraint("lease_token_hash"),
    )
    op.create_index(
        op.f("ix_task_leases_expires_at"), "task_leases", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_task_leases_owner_id"), "task_leases", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_leases_task_id"), "task_leases", ["task_id"], unique=True
    )
    op.create_table(
        "ai_usage_ledger",
        sa.Column("ledger_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("effect_key", sa.String(length=240), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=False),
        sa.Column("business_purpose", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_minor_units", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["ai_provider_attempts.attempt_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["invocation_id"], ["ai_invocations.invocation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ledger_id"),
        sa.UniqueConstraint("attempt_id", name="uq_ai_usage_ledger_attempt"),
        sa.UniqueConstraint("effect_key", name="uq_ai_usage_ledger_effect"),
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_actor_id"),
        "ai_usage_ledger",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_business_purpose"),
        "ai_usage_ledger",
        ["business_purpose"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_invocation_id"),
        "ai_usage_ledger",
        ["invocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_model"), "ai_usage_ledger", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_organization_id"),
        "ai_usage_ledger",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_ledger_provider"),
        "ai_usage_ledger",
        ["provider"],
        unique=False,
    )
    _seed_task_runtime_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _remove_task_runtime_permission_seeds()
    op.drop_index(op.f("ix_ai_usage_ledger_provider"), table_name="ai_usage_ledger")
    op.drop_index(
        op.f("ix_ai_usage_ledger_organization_id"), table_name="ai_usage_ledger"
    )
    op.drop_index(op.f("ix_ai_usage_ledger_model"), table_name="ai_usage_ledger")
    op.drop_index(
        op.f("ix_ai_usage_ledger_invocation_id"), table_name="ai_usage_ledger"
    )
    op.drop_index(
        op.f("ix_ai_usage_ledger_business_purpose"), table_name="ai_usage_ledger"
    )
    op.drop_index(op.f("ix_ai_usage_ledger_actor_id"), table_name="ai_usage_ledger")
    op.drop_table("ai_usage_ledger")
    op.drop_index(op.f("ix_task_leases_task_id"), table_name="task_leases")
    op.drop_index(op.f("ix_task_leases_owner_id"), table_name="task_leases")
    op.drop_index(op.f("ix_task_leases_expires_at"), table_name="task_leases")
    op.drop_table("task_leases")
    op.drop_index(
        op.f("ix_ai_provider_attempts_invocation_id"), table_name="ai_provider_attempts"
    )
    op.drop_table("ai_provider_attempts")
    op.drop_constraint(
        "fk_ai_invocations_result_artifact",
        "ai_invocations",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_ai_invocation_artifacts_organization_id"),
        table_name="ai_invocation_artifacts",
    )
    op.drop_index(
        op.f("ix_ai_invocation_artifacts_invocation_id"),
        table_name="ai_invocation_artifacts",
    )
    op.drop_table("ai_invocation_artifacts")
    op.drop_index(
        op.f("ix_ai_budget_reservations_window_id"), table_name="ai_budget_reservations"
    )
    op.drop_index(
        op.f("ix_ai_budget_reservations_invocation_id"),
        table_name="ai_budget_reservations",
    )
    op.drop_table("ai_budget_reservations")
    op.drop_index(op.f("ix_task_result_refs_task_id"), table_name="task_result_refs")
    op.drop_table("task_result_refs")
    op.drop_index(op.f("ix_task_progress_task_id"), table_name="task_progress")
    op.drop_table("task_progress")
    op.drop_index(
        op.f("ix_task_command_records_task_id"), table_name="task_command_records"
    )
    op.drop_index(
        op.f("ix_task_command_records_organization_id"),
        table_name="task_command_records",
    )
    op.drop_table("task_command_records")
    op.drop_index(op.f("ix_task_attempts_task_id"), table_name="task_attempts")
    op.drop_index("ix_task_attempts_started_task", table_name="task_attempts")
    op.drop_table("task_attempts")
    op.drop_index(op.f("ix_ai_invocations_trace_id"), table_name="ai_invocations")
    op.drop_index(op.f("ix_ai_invocations_task_id"), table_name="ai_invocations")
    op.drop_index(op.f("ix_ai_invocations_state"), table_name="ai_invocations")
    op.drop_index(
        op.f("ix_ai_invocations_owner_expires_at"), table_name="ai_invocations"
    )
    op.drop_index(
        op.f("ix_ai_invocations_organization_id"), table_name="ai_invocations"
    )
    op.drop_index(op.f("ix_ai_invocations_correlation_id"), table_name="ai_invocations")
    op.drop_index(
        op.f("ix_ai_invocations_business_purpose"), table_name="ai_invocations"
    )
    op.drop_index("ix_ai_invocations_business_object", table_name="ai_invocations")
    op.drop_index(op.f("ix_ai_invocations_actor_id"), table_name="ai_invocations")
    op.drop_table("ai_invocations")
    op.drop_index(
        op.f("ix_outbox_consumer_receipts_event_id"),
        table_name="outbox_consumer_receipts",
    )
    op.drop_table("outbox_consumer_receipts")
    op.drop_index(op.f("ix_durable_tasks_trace_id"), table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_task_type"), table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_state"), table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_resource", table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_organization_id"), table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_org_updated_keyset", table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_next_run_at"), table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_correlation_id"), table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_type_aged_claim", table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_aged_claim", table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_type_claim", table_name="durable_tasks")
    op.drop_index("ix_durable_tasks_claim", table_name="durable_tasks")
    op.drop_index(op.f("ix_durable_tasks_actor_id"), table_name="durable_tasks")
    op.drop_table("durable_tasks")
    op.drop_index(
        op.f("ix_task_type_controls_task_type"), table_name="task_type_controls"
    )
    op.drop_index(
        op.f("ix_task_type_controls_organization_id"), table_name="task_type_controls"
    )
    op.drop_table("task_type_controls")
    op.drop_index(
        op.f("ix_task_type_control_commands_task_type"),
        table_name="task_type_control_commands",
    )
    op.drop_index(
        op.f("ix_task_type_control_commands_organization_id"),
        table_name="task_type_control_commands",
    )
    op.drop_table("task_type_control_commands")
    op.drop_index(
        op.f("ix_task_payload_artifacts_organization_id"),
        table_name="task_payload_artifacts",
    )
    op.drop_table("task_payload_artifacts")
    op.drop_index(
        op.f("ix_task_operator_scope_grants_organization_id"),
        table_name="task_operator_scope_grants",
    )
    op.drop_index(
        "ix_task_operator_scope_grants_lookup", table_name="task_operator_scope_grants"
    )
    op.drop_index(
        op.f("ix_task_operator_scope_grants_expires_at"),
        table_name="task_operator_scope_grants",
    )
    op.drop_index(
        op.f("ix_task_operator_scope_grants_actor_id"),
        table_name="task_operator_scope_grants",
    )
    op.drop_table("task_operator_scope_grants")
    op.drop_index(op.f("ix_outbox_events_published_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_organization_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_occurred_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_lease_owner"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_lease_expires_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index("ix_outbox_events_dispatch", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_dead_lettered_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_available_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("ai_rate_limit_windows")
    op.drop_table("ai_prompt_revisions")
    op.drop_table("ai_model_routing_profiles")
    op.drop_table("ai_circuit_states")
    op.drop_table("ai_budget_windows")
    # ### end Alembic commands ###
