"""Bundled Roleplay defaults owned by the neutral bounded context."""

from __future__ import annotations

from typing import Any

ROLEPLAY_SITUATION_PACKS_KEY = "roleplay.situation_packs.ruleset"
ROLEPLAY_EVAL_RELEASE_GATE_KEY = "roleplay.eval.release_gate"

_ROLEPLAY_COMMON_VIOLATION_POLICY: dict[str, str] = {
    "relationship_history_contradiction": "cancel_or_regenerate_once",
    "hidden_information_leak": "cancel_or_regenerate_once",
    "forbidden_topic": "mark_and_continue",
    "persona_style_drift": "mark_for_report",
}

DEFAULT_ROLEPLAY_SITUATION_PACKS: dict[str, Any] = {
    "version": "roleplay_situation_packs_v1",
    "enabled": True,
    "packs": [
        {
            "code": "general_practice",
            "label": "通用对练",
            "version": "legacy_default",
            "status": "published",
            "default_relationship_context": {"prior_interactions": "unspecified"},
            "default_visible_information_scope": {
                "initial_visible_keys": [],
                "conditionally_visible_keys": [],
                "hidden_by_default_keys": [],
            },
            "default_forbidden_claim_patterns": [],
            "default_forbidden_topic_codes": [],
            "default_forbidden_stage_codes": [],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": {
                **_ROLEPLAY_COMMON_VIOLATION_POLICY,
                "relationship_history_contradiction": "mark_for_report",
            },
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "first_visit",
            "label": "首次拜访",
            "version": "v1",
            "status": "published",
            "initial_stage_hint": "opening",
            "default_relationship_context": {
                "prior_interactions": "none",
                "has_prior_meeting": False,
                "has_seen_proposal": False,
                "has_discussed_budget": False,
                "has_existing_partnership": False,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                    "success_criteria",
                ],
                "conditionally_visible_keys": ["hidden_information"],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "budget",
                    "decision_chain",
                    "competitor_quote",
                ],
            },
            "default_forbidden_claim_patterns": [
                "上次拜访",
                "之前我们聊",
                "上次方案",
                "之前报价",
                "之前合作",
                "上次沟通",
                "上次见面",
                "之前你给",
            ],
            "default_forbidden_topic_codes": ["contract_closing"],
            "default_forbidden_stage_codes": [
                "price_negotiation",
                "contract_closing",
            ],
            "default_conflict_response_strategy": "customer_confused_correction",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "follow_up",
            "label": "复访跟进",
            "version": "v1",
            "status": "published",
            "default_relationship_context": {
                "prior_interactions": "one_meeting",
                "has_prior_meeting": True,
                "has_seen_proposal": False,
                "has_discussed_budget": False,
                "has_existing_partnership": False,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                ],
                "conditionally_visible_keys": [
                    "success_criteria",
                    "hidden_information",
                ],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "budget",
                    "decision_chain",
                ],
            },
            "default_forbidden_claim_patterns": [],
            "default_forbidden_topic_codes": ["contract_closing"],
            "default_forbidden_stage_codes": ["contract_closing"],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "proposal_review",
            "label": "方案评审",
            "version": "v1",
            "status": "published",
            "default_relationship_context": {
                "prior_interactions": "one_meeting",
                "has_prior_meeting": True,
                "has_seen_proposal": True,
                "has_discussed_budget": False,
                "has_existing_partnership": False,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                    "success_criteria",
                ],
                "conditionally_visible_keys": ["hidden_information"],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "decision_chain",
                    "competitor_quote",
                ],
            },
            "default_forbidden_claim_patterns": ["之前合作"],
            "default_forbidden_topic_codes": ["contract_closing"],
            "default_forbidden_stage_codes": ["contract_closing"],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "price_negotiation",
            "label": "价格谈判",
            "version": "v1",
            "status": "published",
            "default_relationship_context": {
                "prior_interactions": "multiple_meetings",
                "has_prior_meeting": True,
                "has_seen_proposal": True,
                "has_discussed_budget": True,
                "has_existing_partnership": False,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                    "success_criteria",
                ],
                "conditionally_visible_keys": ["hidden_information"],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "internal_floor_price",
                    "decision_chain",
                ],
            },
            "default_forbidden_claim_patterns": [
                "已经接受报价",
                "已经同意合同",
                "之前合作",
            ],
            "default_forbidden_topic_codes": [],
            "default_forbidden_stage_codes": ["contract_closing"],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "renewal",
            "label": "续约沟通",
            "version": "v1",
            "status": "published",
            "default_relationship_context": {
                "prior_interactions": "existing_customer",
                "has_prior_meeting": True,
                "has_seen_proposal": False,
                "has_discussed_budget": False,
                "has_existing_partnership": True,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                ],
                "conditionally_visible_keys": [
                    "success_criteria",
                    "hidden_information",
                ],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "renewal_risk",
                    "decision_chain",
                ],
            },
            "default_forbidden_claim_patterns": ["默认满意续约", "已经决定续约"],
            "default_forbidden_topic_codes": [],
            "default_forbidden_stage_codes": ["contract_closing"],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
        {
            "code": "complaint_recovery",
            "label": "投诉安抚",
            "version": "v1",
            "status": "published",
            "default_relationship_context": {
                "prior_interactions": "existing_customer",
                "has_prior_meeting": True,
                "has_seen_proposal": False,
                "has_discussed_budget": False,
                "has_existing_partnership": True,
                "meeting_history_summary": None,
            },
            "default_visible_information_scope": {
                "initial_visible_keys": [
                    "industry",
                    "company_profile",
                    "customer_role",
                    "pain_points",
                    "objections",
                ],
                "conditionally_visible_keys": [
                    "success_criteria",
                    "hidden_information",
                ],
                "hidden_by_default_keys": [
                    "hidden_information",
                    "compensation_boundary",
                    "decision_chain",
                ],
            },
            "default_forbidden_claim_patterns": [
                "无条件赔偿",
                "马上全额退款",
                "已经批准赔偿",
            ],
            "default_forbidden_topic_codes": ["unauthorized_compensation"],
            "default_forbidden_stage_codes": ["contract_closing"],
            "default_conflict_response_strategy": "neutral_clarification",
            "default_runtime_violation_policy": _ROLEPLAY_COMMON_VIOLATION_POLICY,
            "compatible_practice_modes": ["customer_roleplay"],
            "compatible_scenario_types": ["sales"],
        },
    ],
}

DEFAULT_ROLEPLAY_EVAL_RELEASE_GATE: dict[str, Any] = {
    "version": "roleplay_eval_release_gate_v1",
    "enabled": True,
    "deterministic_gate_mode": "blocking",
    "llm_grader_mode": "warn_only",
    "blocking_violation_codes": [
        "ROLEPLAY_HISTORY_CONTRADICTION",
        "ROLEPLAY_HIDDEN_INFORMATION_LEAK",
        "ROLEPLAY_FORBIDDEN_STAGE",
    ],
    "artifact_retention_days": 30,
}
